/* Endless modifiers, named themes, danger tiers, and help text. */

#include "endless.h"
#include "endless_internal.h"
#include "endless_levelprofile.h"
#include "fonthand.h"

#include <stdio.h>
#include <string.h>


const EndlessMod endlessModTable[] = {
	// Monitor labels describe effects and must fit a 113-pixel TINY_FONT column.
	{ ENDLESS_MOD_FORTIFIED,     10, "more enemy health" },
	{ ENDLESS_MOD_FRENZY,        10, "faster enemy fire" },
	{ ENDLESS_MOD_SWIFT,          8, "faster enemy shots" },
	{ ENDLESS_MOD_DEVASTATING,   10, "harder enemy hits" },
	{ ENDLESS_MOD_ENRAGE,        10, "enemy fire rate climbs" },
	{ ENDLESS_MOD_GRAVITY,        8, "downward pull" },
	{ ENDLESS_MOD_ELITEPACK,     20, "half enemies elite" },
	{ ENDLESS_MOD_OVERCLOCK,     16, "faster enemy attacks" },  // fire rate, shot speed, and scrolling
	{ ENDLESS_MOD_SLIPSTREAM,     6, "faster scrolling" },
	{ ENDLESS_MOD_KAMIKAZE,      12, "enemies home in" },   // moderate homing without ram damage
	{ ENDLESS_MOD_HOMING,         6, "light homing" },
	{ ENDLESS_MOD_RAMPAGE,       50, "enemies ram you" },   // gamble-only strong homing and ram damage
	{ ENDLESS_MOD_OVERLOAD,      30, "extreme enemy attacks" },  // stronger Overclock variant
	{ ENDLESS_MOD_APEX,          40, "all enemies elite" },
	{ ENDLESS_MOD_LEGION,        50, "all champion enemies" },
	{ ENDLESS_MOD_WARP,          20, "much faster scrolling" },  // Slipstream cranked way up (rare injected)
	{ ENDLESS_MOD_BACKFIRE, 12, "kills jam your guns" },
	{ ENDLESS_MOD_BURNOUT,   18, "kills weaken guns" },
	{ ENDLESS_MOD_MISFIRE,   14, "kills cut your damage" },
	{ ENDLESS_MOD_OVERHEAT,  14, "hull burns over time" },  // the reactor cooks you (gamble deal + rare Redline sector)
	{ ENDLESS_MOD_TOPSY,     10, "upside-down view" },      // controls invert with the playfield
	{ ENDLESS_MOD_SLUGGISH,  15, "your ship slowed" },
	{ ENDLESS_MOD_SHIELDLESS, 12, "no shield regen" },
	{ ENDLESS_MOD_DEADGEN,   30, "generator dead" },        // no shield regen AND the main gun is starved of power (super-rare)
	{ ENDLESS_MOD_MARTYRDOM, 18, "kills fire a burst" },    // a slain enemy's death throe: a radial burst (4/6/8 by tier)
	{ ENDLESS_MOD_SEEKER,    14, "shots curve at you" },    // enemy projectiles bend once toward you mid-flight
	{ ENDLESS_MOD_STATIC,    11, "hits drain power" },
	{ ENDLESS_MOD_RETALIATION, 15, "kills quicken fire" },  // a kill spree whips enemy fire faster (distinct from time-based Enrage)
	// The finale marker has no monitor row. Its weight controls reward and slate ordering.
	{ ENDLESS_MOD_THEEND,   150, NULL },
	// Boons generally reduce or omit clear cash.
	{ ENDLESS_MOD_FRAGILE,       -5, "less enemy health" },
	{ ENDLESS_MOD_TURBODRIVE,      0, "kills quicken guns" },
	{ ENDLESS_MOD_OVERCHARGE,     0, "more weapon damage" },
	{ ENDLESS_MOD_DILATION,       0, "slower enemy shots" },
	{ ENDLESS_MOD_FAVOR,          0, "cheaper next shop" },
	{ ENDLESS_MOD_OVERDRIVE,   0, "stacking damage + firerate" },
	{ ENDLESS_MOD_OVERBLAST,   0, "kills stack damage" },
	{ ENDLESS_MOD_BOUNTY,        30, "big cash payout" },
	{ ENDLESS_MOD_CURSED,        40, "cash now, empty shop" },
	{ ENDLESS_MOD_NOCHAMP,        0, "no champion enemies" },     // no clear-cash: the boon already costs you the elite/champion bounties
	{ ENDLESS_MOD_NOELITE,        0, "no elites or champions" },
	// Survival boons reduce clear cash. Informational and economy-only boons have zero weight.
	{ ENDLESS_MOD_AEGIS,         -5, "shield blocks overflow" },
	{ ENDLESS_MOD_FLAKSCREEN,    -5, "fewer added shots" },
	{ ENDLESS_MOD_AUXREACTOR,     0, "free shield recharge" },
	{ ENDLESS_MOD_LOWPROFILE,    -8, "smaller hitbox" },
	{ ENDLESS_MOD_GIANTKILLER,   -6, "weaker elite armor" },
	{ ENDLESS_MOD_SHOCKWAVE,     -4, "elite kills wipe shots" },
	{ ENDLESS_MOD_STARCHARTS,     0, "more routes next" },
	{ ENDLESS_MOD_BREAKTHROUGH, -10, "perk on clear" },
	{ ENDLESS_MOD_SOFTLANDING,   -4, "safer collisions" },
	{ ENDLESS_MOD_CLEANSIGNALS,  -5, "weaker elite attacks" },
};

/* The special-enemy bits form one ladder: No Elites, Legion, Apex, Elite Pack. A weaker bit beside
 * a stronger one changes nothing at runtime, yet still lists a monitor row and charges danger and
 * payout. See "Modifiers and courses" in doc/notes.md. */
Uint64 endlessCanonicalMods(Uint64 mods)
{
	if (mods & ENDLESS_MOD_NOELITE)   // no specials at all, so every tier bit below is inert
		mods &= ~(Uint64)(ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_ELITEPACK
		                  | ENDLESS_MOD_APEX | ENDLESS_MOD_LEGION);
	// A champion cap leaves Legion's 100 percent share, which is what Apex already says.
	if ((mods & ENDLESS_MOD_NOCHAMP) && (mods & ENDLESS_MOD_LEGION))
		mods = (mods & ~(Uint64)ENDLESS_MOD_LEGION) | ENDLESS_MOD_APEX;
	if (mods & ENDLESS_MOD_LEGION)
		mods &= ~(Uint64)(ENDLESS_MOD_APEX | ENDLESS_MOD_ELITEPACK);
	else if (mods & ENDLESS_MOD_APEX)
		mods &= ~(Uint64)ENDLESS_MOD_ELITEPACK;
	return mods;
}

const EndlessTheme endlessHostileThemes[] = {
	// Single dangers.
	{ ENDLESS_MOD_FORTIFIED,   "Fortified" },
	{ ENDLESS_MOD_FRENZY,      "Frenzy" },
	{ ENDLESS_MOD_SWIFT,       "Swift Death" },
	{ ENDLESS_MOD_DEVASTATING, "Devastating" },
	{ ENDLESS_MOD_ENRAGE,      "Enrage" },
	{ ENDLESS_MOD_GRAVITY,     "Gravity Well" },
	{ ENDLESS_MOD_ELITEPACK,   "Elite Pack" },
	{ ENDLESS_MOD_OVERCLOCK,   "Overclock" },
	{ ENDLESS_MOD_SLIPSTREAM,  "Slipstream" },    // faster scroll: the level rushes at you (a threat, not the old boon)
	{ ENDLESS_MOD_TOPSY,       "Topsy Turvy" },
	{ ENDLESS_MOD_SLUGGISH,    "Molasses" },

	// Pairs.
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,       "Onslaught" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,        "Juggernaut" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING,  "Siege" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,           "Barrage" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,     "Fusillade" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,      "Piercing Storm" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_FORTIFIED,       "War of Attrition" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_SWIFT,           "Escalation" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,     "Wrath" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FORTIFIED,      "Dense Matter" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_SWIFT,          "Event Horizon" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,    "Crushing Weight" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FRENZY,         "Whirlpool" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED,    "Praetorians" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,        "Vanguard" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_DEVASTATING,  "Elite Guard" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY,       "Warband" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_FORTIFIED,    "Meltdown" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_DEVASTATING,  "Reactor Breach" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_GRAVITY,      "Riptide" },  // avoids the Overdrive boon name
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_ELITEPACK,    "Prototype Swarm" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_FRENZY,      "Fast Lane" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_DEVASTATING, "Runaway" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_FORTIFIED,   "Bypass" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE,          "Bloodrage" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_OVERCLOCK,       "Redline" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_OVERCLOCK,        "Hypervelocity" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY,         "Accretion" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK,       "Elite Fury" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_OVERCLOCK,       "Overburn" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK,      "Neutron Star" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_DEVASTATING,    "Glass Cannon" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_FORTIFIED,		"Capsize" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_FRENZY,			"Vertigo" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_SWIFT,			"Corkscrew" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_DEVASTATING,		"Upheaval" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_ENRAGE,			"Whirligig" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_ELITEPACK,		"Off Kilter" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_OVERCLOCK,		"Barrel Roll" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_GRAVITY,			"Somersault" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_SLUGGISH,			"Head Rush" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_FORTIFIED,		"Anchored" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_FRENZY,		"Slog" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_SWIFT,			"Bogged Down" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_DEVASTATING,	"Lead Boots" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_ENRAGE,		"Pressure Cooker" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_ELITEPACK,		"Ballast" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_OVERCLOCK,		"Millstone" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FORTIFIED,   "Attrition" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FRENZY,      "Exposed" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_SWIFT,       "Pincushion" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_DEVASTATING, "Glass Hull" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_ENRAGE,      "Overexposed" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_ELITEPACK,   "Outmatched" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_OVERCLOCK,   "No Cover" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_GRAVITY,     "Naked Descent" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_TOPSY,       "Spin Out" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_SLUGGISH,    "Sitting Target" },

	// Triples.
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,       "Nightmare" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Maelstrom" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,  "Fortress Guns" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Deadly Escalation" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,    "Singularity" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Elite Siege" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "Blitzkrieg" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,   "Colossus" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,    "Siege Engine" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_GRAVITY,        "Heavy Siege" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE,         "Bloodwall" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,      "Vortex" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,       "Firestorm" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY,            "Cyclone" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY,            "Death Spiral" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Death Squad" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "War Machine" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,   "Doomguard" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,    "Elite Wrath" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Overkill" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "Full Auto" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Iron Storm" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_ELITEPACK, "Bloodtide" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_OVERCLOCK, "Warpath" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE, "Ironclad" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY, "Rampart" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ELITEPACK, "Hailstorm" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_OVERCLOCK, "Thunderclap" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY, "Pandemonium" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK, "Requiem" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_OVERCLOCK, "Damnation" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK, "Perdition" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_OVERCLOCK, "Warhead" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Sledgehammer" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE, "Warmonger" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ELITEPACK, "Devastator" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_OVERCLOCK, "Ravager" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY, "Desolation" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK, "Bombardment" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_OVERCLOCK, "Storm Surge" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK, "Iron Rain" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_OVERCLOCK, "Steel Storm" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Death March" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK, "Hellfire" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_OVERCLOCK, "Brimstone" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK, "Wildfire" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_OVERCLOCK, "Firewall" },
	{ ENDLESS_MOD_SWIFT | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Overrun" },
	{ ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY, "Stampede" },
	{ ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_OVERCLOCK, "Warzone" },
	{ ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_OVERCLOCK, "Killzone" },
	{ ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Crossfire" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK, "Massacre" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_OVERCLOCK, "Butchery" },
	{ ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Bloodbath" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Slaughter" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Tumbler" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Keelhaul" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,   "Free Fall" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_FRENZY,       "Disorient" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,       "Bullet Wade" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Deadlock" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ELITEPACK,    "Molasses Run" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,        "Kill Box" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Last Ditch" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,     "No Quarter" },

	// Quads.
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Cataclysm" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,   "Elite Nightmare" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY,     "Abaddon" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE, "Armageddon" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE,    "Apocalypse" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE,      "Berserker Rush" },
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE,   "Event Collapse" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE, "Black Star" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Praetorian Guard" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,  "Elite Storm" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,  "Bullet Hell" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Overlord" },

	// Static Discharge is also in the combinable pool.
	{ ENDLESS_MOD_STATIC,                            "Static Discharge" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_FRENZY,       "Power Leech" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_DEVASTATING,  "Short Circuit" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_SWIFT,        "Live Wire" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_FORTIFIED,    "Grounded" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_ELITEPACK,    "Feedback" },

	// Retaliation is in the shuffle pool but not the combinable pool.
	{ ENDLESS_MOD_RETALIATION,                            "Retaliation" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_FRENZY,       "Backlash" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_SWIFT,        "Payback" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_DEVASTATING,  "Riposte" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_ENRAGE,       "Bad Blood" },   // the +5 Retaliation+Enrage synergy sector
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_FORTIFIED,    "Grudge" },

	// Remaining signature pairs omit redundant Overclock+Slipstream and rare Tar Pit.
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_FRENZY,         "Dying Breath" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_ENRAGE,         "Death Throes" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_GRAVITY,        "Deadfall" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_OVERCLOCK,      "Powder Trail" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_TOPSY,          "Death Roll" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_STATIC,         "Death Spark" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_SHIELDLESS,     "Shrapnel" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_RETALIATION,    "Vicious Cycle" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_SEEKER,         "Dead Aim" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_SLIPSTREAM,     "Drive-By" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_SLUGGISH,       "No Escape" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_ENRAGE,            "Guided Fury" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_GRAVITY,           "Curveball" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_OVERCLOCK,         "Fast Track" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_ELITEPACK,         "Marked Man" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_TOPSY,             "Twisted Aim" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_STATIC,            "Live Rounds" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_SHIELDLESS,        "Hunted" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_RETALIATION,       "Hot Pursuit" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_SLIPSTREAM,        "Quick Lock" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_SLUGGISH,          "Easy Mark" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_ENRAGE,            "Rising Static" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_GRAVITY,           "Ion Well" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_OVERCLOCK,         "Overdraft" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_TOPSY,             "Short Out" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_SHIELDLESS,        "Bare Wires" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_RETALIATION,       "Backcurrent" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_SLIPSTREAM,        "Third Rail" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_SLUGGISH,          "Power Sap" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_GRAVITY,      "Sinking Feeling" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_OVERCLOCK,    "Chain Fire" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_ELITEPACK,    "Command Chain" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_TOPSY,        "Backspin" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_SHIELDLESS,   "Open Wound" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_SLIPSTREAM,   "Hot Lap" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_SLUGGISH,     "Treadmill" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_SWIFT,         "Slipshot" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_ENRAGE,        "Fast Forward" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_GRAVITY,       "Downdraft" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_ELITEPACK,     "Fast Company" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_TOPSY,         "Overturn" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_SHIELDLESS,    "Run for It" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_SLUGGISH,      "Falling Behind" },

	// Named triples cover the combinable pool and continue to exclude Tar Pit.
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,            "Arc Storm" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING,   "Iron Circuit" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY,        "Overcurrent" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,     "Magnetar" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_FRENZY,           "Rolling Blackout" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_DEVASTATING,  "Total Loss" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_TOPSY | ENDLESS_MOD_FRENZY,            "Scrambled" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,            "Needle Storm" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING,   "Guided Siege" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,         "Elite Trackers" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,     "Homing Well" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_FRENZY,           "Hunter's Rhythm" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_SWIFT,        "Nowhere to Hide" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_TOPSY | ENDLESS_MOD_DEVASTATING,       "Crooked Sky" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,         "Final Volley" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,     "Hard to Kill" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_DEVASTATING, "Funeral Pyre" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FRENZY,       "Falling Ashes" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,   "Scorched Earth" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_SWIFT,     "Splinters" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_TOPSY | ENDLESS_MOD_FRENZY,         "Death Blossom" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,       "Answering Fire" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Blood Feud" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,    "Honor Guard" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING, "Rebound" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_SWIFT,       "Boiling Over" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FRENZY,  "Raw Nerve" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_TOPSY | ENDLESS_MOD_SWIFT,        "Whiplash" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,          "Inverted Guard" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,       "Head Over Heels" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FRENZY,           "Downside Up" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_DEVASTATING,   "Exposed Flank" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FRENZY,      "Bottoming Out" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_SWIFT,        "Bleeding Out" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_DEVASTATING, "Thin Skinned" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,   "Head-On" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY,    "Fast Movers" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING, "Steep Descent" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_SWIFT,        "Full Throttle" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_TOPSY | ENDLESS_MOD_DEVASTATING,     "Dead Slow" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_SWIFT,      "Easy Pickings" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_DEVASTATING,    "Long Haul" },

	// Four bits is the combinable-pool ceiling.
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Grid Lock" },
	{ ENDLESS_MOD_STATIC | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Dead Battery" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Smart Siege" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "Target Locked" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Dying Light" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,    "Martyr Guard" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,   "Even the Score" },
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY, "Blood Oath" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE,              "Spin Cycle" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Upended" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,    "Cut to the Bone" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,      "Slow Death" },
};

// Homing rammers use a separate rare injection pool.
const EndlessTheme endlessKamikazeThemes[] = {
	{ ENDLESS_MOD_KAMIKAZE,                              "Kamikaze" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_FORTIFIED,      "Battering Ram" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_FRENZY,         "Zealots" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_SWIFT,          "Dive Bombers" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_DEVASTATING,    "Suicide Run" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_GRAVITY,        "Black Hole" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_ELITEPACK,      "Berserkers" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Kamikaze Storm" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_ENRAGE,        "Fanatics" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_OVERCLOCK,     "Rocket Swarm" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "Death Charge" },
	{ ENDLESS_MOD_KAMIKAZE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Siege Ram" },
};

// Light homing uses a separate moderate-frequency pool without ram damage.
const EndlessTheme endlessHomingThemes[] = {
	{ ENDLESS_MOD_HOMING,                              "Stalkers" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_FORTIFIED,      "Bloodhounds" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_FRENZY,         "Harriers" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_SWIFT,          "Pursuers" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_DEVASTATING,    "Predators" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_GRAVITY,        "Undertow" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_ELITEPACK,      "Wolfpack" },
	{ ENDLESS_MOD_HOMING | ENDLESS_MOD_ENRAGE,         "Bloodlust" },
};

const EndlessTheme endlessBoonThemes[] = {
	{ ENDLESS_MOD_FRAGILE,    "Fragile Foe" },
	{ ENDLESS_MOD_BOUNTY,     "Bounty Run" },
	{ ENDLESS_MOD_TURBODRIVE,  "Turbodrive" },   // the shop's Turbodrive buy sets this same bit (endlessTryBuyTurbodrive)
	{ ENDLESS_MOD_OVERDRIVE, "Overdrive" },   // the shop's Overdrive buy sets this same bit (endlessTryBuyOverdrive)
	{ ENDLESS_MOD_OVERBLAST, "Overblast" },   // the shop's Overblast buy sets this same bit (endlessTryBuyOverblast)
	{ ENDLESS_MOD_OVERCHARGE, "Overcharged" },
	{ ENDLESS_MOD_DILATION,   "Time Dilation" },
	{ ENDLESS_MOD_FAVOR,      "Merchant's Favor" },
	{ ENDLESS_MOD_CURSED,     "Cursed Bounty" },
	{ ENDLESS_MOD_NOCHAMP,    "Leaderless" },
	{ ENDLESS_MOD_NOELITE,    "Rank and File" },
	// Boon pairs.
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_OVERCHARGE, "Ascendant" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_OVERCHARGE,  "Bullet Time" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_TURBODRIVE,   "In the Zone" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_BOUNTY,       "Easy Money" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_BOUNTY,         "Windfall" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_TURBODRIVE,    "Blood Frenzy" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_OVERCHARGE,   "Executioner" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_FAVOR,        "Clearance" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_BOUNTY,     "Killing Spree" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_BOUNTY,    "Mercenary" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_OVERCHARGE, "Power Surge" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_OVERCHARGE, "Deadeye" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_DILATION,   "Sharpshooter" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_BOUNTY,     "Bounty Hunter" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_DILATION, "Killstreak" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_OVERDRIVE, "Bloodrush" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_CURSED, "Adrenaline" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FAVOR, "Momentum" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_BOUNTY, "Berserk" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_CURSED, "Fortune" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FAVOR, "Jackpot" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_CURSED, "Gold Rush" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FAVOR, "Bonanza" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_BOUNTY, "Lucky Break" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_OVERDRIVE, "Fire Sale" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_CURSED, "Discount" },
	// Fewer NOELITE pairs keep the stronger boon rarer. Do not pair it with NOCHAMP.
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_OVERCHARGE, "Purge" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_BOUNTY,     "Trophy Room" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_FRAGILE,    "Mop Up" },
	{ ENDLESS_MOD_NOELITE | ENDLESS_MOD_OVERCHARGE, "Marksman" },
	{ ENDLESS_MOD_NOELITE | ENDLESS_MOD_FAVOR,      "Clean Slate" },
	// Boon triples.
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_OVERCHARGE, "Ascension" },
	// Breakthrough remains in its separate rare pool.
	{ ENDLESS_MOD_AEGIS,        "Aegis Gate" },
	{ ENDLESS_MOD_FLAKSCREEN,   "Flak Screen" },
	{ ENDLESS_MOD_AUXREACTOR,   "Auxiliary Reactor" },
	{ ENDLESS_MOD_LOWPROFILE,   "Low Profile" },
	{ ENDLESS_MOD_GIANTKILLER,  "Giant Killer" },
	{ ENDLESS_MOD_SHOCKWAVE,    "Disruption Pulse" },   // "Shockwave" is a generated hostile name
	{ ENDLESS_MOD_STARCHARTS,   "Star Charts" },
	{ ENDLESS_MOD_SOFTLANDING,  "Soft Landing" },
	{ ENDLESS_MOD_CLEANSIGNALS, "Clean Signals" },
	// Cross-system pairs avoid redundant effects.
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_AUXREACTOR,        "Full Deflector" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_LOWPROFILE,        "Untouchable" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_DILATION,     "Needle Threader" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_OVERCHARGE,   "Pinpoint" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_OVERCHARGE,  "Titan Bane" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_BOUNTY,      "Trophy Cull" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_OVERCHARGE,    "Ion Burst" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_DILATION,     "Open Air" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_FRAGILE,      "Clear Corridor" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_FAVOR,        "Deep Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_BOUNTY,       "Recon Data" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_FRAGILE,     "Cushioned" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_FRAGILE,    "Jamming Field" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_OVERCHARGE,   "Full Power" },
	// Remaining pairs match the endlessMakeBoonCombo pool. NOELITE stays limited.
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_BOUNTY,            "Safe Haul" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_FAVOR,             "Insurance" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SHOCKWAVE,         "Bulwark" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_GIANTKILLER,       "Bastion" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_STARCHARTS,        "Guarded Route" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_CLEANSIGNALS,      "Quiet Shield" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SOFTLANDING,       "Padded Hull" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_FLAKSCREEN,        "Double Cover" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FRAGILE,      "Wisp" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_BOUNTY,       "Ghost Run" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FAVOR,        "Low Overhead" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SHOCKWAVE,    "Pressure Drop" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_GIANTKILLER,  "Blind Spot" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_AUXREACTOR,   "Efficient" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_STARCHARTS,   "Scout Profile" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FRAGILE,      "Full Reserves" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_BOUNTY,       "Overflow" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FAVOR,        "Surplus" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_DILATION,     "Cool Head" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_SHOCKWAVE,    "Capacitor" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_GIANTKILLER,  "Amped" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_CLEANSIGNALS, "Steady State" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_BOUNTY,      "Safe Delivery" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_OVERCHARGE,  "Reinforced" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_DILATION,    "Easy Does It" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_LOWPROFILE,  "Nimble" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_GIANTKILLER, "Rough and Ready" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_FRAGILE,       "Clean Sweep" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_BOUNTY,        "Shock Value" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_DILATION,      "Breathing Room" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_GIANTKILLER,   "Kingslayer" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_FRAGILE,      "Easy Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_DILATION,     "Long View" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_OVERCHARGE,   "Bright Prospect" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_LOWPROFILE,   "Silent Survey" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_BOUNTY,       "Umbrella" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_FAVOR,        "Cheap Cover" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_OVERCHARGE,   "Counterbattery" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_FRAGILE,     "Paper Tigers" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_FAVOR,       "Bargain Hunt" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_OVERCHARGE, "Upper Hand" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_BOUNTY,     "Soft Targets" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_DILATION,   "Dead Calm" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_LOWPROFILE, "Off the Grid" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_DILATION,        "No Brass" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_FAVOR,           "Vacancy" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_LOWPROFILE,      "Unnoticed" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_GIANTKILLER,     "Toppled" },
	// Name triples produced by endlessMakeBoonCombo.
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_DILATION,      "Untouched" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FRAGILE,       "Safe Conduct" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_AUXREACTOR,   "Cocoon" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_FRAGILE,   "Clean Escape" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_DILATION, "Ghost Corridor" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FAVOR,        "Golden Run" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FAVOR,        "Prospector" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_OVERCHARGE, "Paper Crown" },
};

// Breakthrough uses a separate gated pool because it awards an additional perk pick.
const EndlessTheme endlessBreakthroughThemes[] = {
	{ ENDLESS_MOD_BREAKTHROUGH,                            "Breakthrough" },
	{ ENDLESS_MOD_BREAKTHROUGH | ENDLESS_MOD_BOUNTY,       "Revelation" },
	{ ENDLESS_MOD_BREAKTHROUGH | ENDLESS_MOD_FRAGILE,      "Discovery" },
	{ ENDLESS_MOD_BREAKTHROUGH | ENDLESS_MOD_OVERCHARGE,   "Epiphany" },
	{ ENDLESS_MOD_BREAKTHROUGH | ENDLESS_MOD_FAVOR,        "Eureka" },
};

// Warp is a rare scroll threat injected outside the hostile shuffle pool.
static const EndlessTheme endlessWarpThemes[] = {
	{ ENDLESS_MOD_WARP,       "Warp Speed" },
};

// Overload is injected separately from the normal hostile rotation.
const EndlessTheme endlessOverloadThemes[] = {
	{ ENDLESS_MOD_OVERLOAD,                           "Overload" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED,   "Core Breach" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_DEVASTATING, "Chain Reaction" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_ELITEPACK,   "Singularity Core" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FRENZY,      "Detonation" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_SWIFT,       "Overvelocity" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_GRAVITY,     "Implosion" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_ENRAGE,      "Overheat" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Fusion Core" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Total Meltdown" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY, "Core Meltdown" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT, "Fission" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ENRAGE, "Critical Mass" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_GRAVITY, "Chain Blast" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ELITEPACK, "Cascade" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_OVERCLOCK, "Feedback Loop" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT, "Power Spike" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING, "Blackout" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE, "Flashpoint" },
	{ ENDLESS_MOD_OVERLOAD | ENDLESS_MOD_FRENZY | ENDLESS_MOD_GRAVITY, "Ground Zero" },
};

// Explicit rare injections combine elite tiers with dangers or use five ordinary dangers.
const EndlessTheme endlessRareThemes[] = {
	// Bare elite tiers.
	{ ENDLESS_MOD_APEX,   "Apex Swarm" },
	{ ENDLESS_MOD_LEGION, "Legion" },
	// Elite tier plus one danger.
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_FORTIFIED,                          "Apex Titans" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_SWIFT,                              "Apex Hunters" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_DEVASTATING,                        "Annihilation" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_OVERLOAD,                           "Extinction" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_FRENZY, "Alpha Strike" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_ENRAGE, "Omega" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_GRAVITY, "Final Hour" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_SHIELDLESS, "Last Stand" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_OVERCLOCK, "Endgame" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_FORTIFIED,                        "Iron Legion" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_SWIFT,                            "Blitz Legion" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_DEVASTATING,                      "Ragnarok" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_OVERLOAD,                         "Judgment Day" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_FRENZY, "Mass Extinction" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_ENRAGE, "The Reaping" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_GRAVITY, "Harbinger" },
	// Elite tier plus two dangers.
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Apex Siege" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,   "Apex Predator" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,    "Apex Onslaught" },
	{ ENDLESS_MOD_APEX | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING, "Event Apex" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Final Legion" },
	{ ENDLESS_MOD_LEGION | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Legion Siege" },
	// Five-danger Cataclysm entries exclude elite-tier bits.
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE,  "Hell Unleashed" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_GRAVITY, "Void Storm" },
	{ ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Total War" },
	{ ENDLESS_MOD_OVERCLOCK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Doomsday" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY, "Nemesis" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK, "Leviathan" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_OVERCLOCK, "Behemoth" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_ELITEPACK, "Titanfall" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_OVERCLOCK, "Wrath of God" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_OVERCLOCK, "Purgatory" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY, "Tartarus" },
	{ ENDLESS_MOD_TOPSY | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,   "Kaleidoscope" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,  "Oubliette" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE, "Naked Siege" },
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_TOPSY | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,  "Sensory Overload" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY,   "Doomtide" },
	{ ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_ELITEPACK,    "Deathstorm" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY, "Ruination" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_SHIELDLESS, "Death Knell" },
	{ ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE | ENDLESS_MOD_TOPSY | ENDLESS_MOD_SLUGGISH, "Black Sun" },
};

// The End keeps a fixed enemy-stat core and rolls the remaining dangers per milestone, leaving out
// the scroll-pace group so the finale runs at its level's own speed.
// Its marker controls naming, rank, and reward independently of the exact combination.
#define ENDLESS_THEEND_CORE (ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT \
                             | ENDLESS_MOD_DEVASTATING | ENDLESS_MOD_ENRAGE)

Uint64 endlessMakeTheEndMods(void)
{
	Uint64 m = ENDLESS_MOD_THEEND | ENDLESS_THEEND_CORE;

	// Always select an all-elite or, less often, all-champion tier.
	// Elite Pack is excluded because deep-run normalization can remove it.
	m |= (endlessRand() % 3 == 0) ? ENDLESS_MOD_LEGION : ENDLESS_MOD_APEX;

	// Ship hazards are independent. Gravity scales with Sluggish so full throttle can still climb.
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_GRAVITY;
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_TOPSY;
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_SLUGGISH;

	// Reactive dangers are independent. DEADGEN is absent, so Static remains compatible.
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_MARTYRDOM;
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_SEEKER;
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_STATIC;
	if (endlessRand() % 2)
		m |= ENDLESS_MOD_RETALIATION;

	return m;
}

// Hostile kill-fire variants slow fire and may reduce damage as the combo grows.
// The bare bits also appear as forced gamble outcomes.
const EndlessTheme endlessEvilThemes[] = {
	{ ENDLESS_MOD_BACKFIRE,                           "Backfire" },
	{ ENDLESS_MOD_BURNOUT,                            "Burnout" },
	{ ENDLESS_MOD_MISFIRE,                            "Misfire" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_DEVASTATING, "Sitting Duck" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_FORTIFIED,   "Uphill Battle" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_SWIFT,       "Overwhelmed" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_GRAVITY,     "Dead Weight" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_FRENZY,      "Friendly Fire" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_ENRAGE,      "Slow Burn" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_ELITEPACK,   "Cornered" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_OVERCLOCK,   "Vapor Lock" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_DEVASTATING,  "Death Rattle" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_FORTIFIED,    "Losing Battle" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_ENRAGE,       "Downward Spiral" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_ELITEPACK,    "Outclassed" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_FRENZY,       "Flatline" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_SWIFT,        "Cinders" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_GRAVITY,      "Tailspin" },
	{ ENDLESS_MOD_BURNOUT | ENDLESS_MOD_OVERCLOCK,    "System Failure" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_DEVASTATING,  "Peashooter" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_FORTIFIED,    "Stonewall" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_SWIFT,        "Outgunned" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_FRENZY,       "Popgun" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_ENRAGE,       "Fizzle" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_GRAVITY,      "Downhill" },
	{ ENDLESS_MOD_MISFIRE | ENDLESS_MOD_ELITEPACK,    "No Contest" },
	{ ENDLESS_MOD_BACKFIRE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Forced March" },
	{ ENDLESS_MOD_BURNOUT  | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,     "Last Legs" },
	{ ENDLESS_MOD_MISFIRE  | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,       "Stalemate" },
	{ ENDLESS_MOD_BURNOUT  | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "No Way Out" },
};

// Reactor Redline combines Turbodrive with the Overheat damage-over-time effect.
const EndlessTheme endlessRedlineThemes[] = {
	{ ENDLESS_MOD_OVERHEAT | ENDLESS_MOD_TURBODRIVE,                      "Reactor Redline" },
	{ ENDLESS_MOD_OVERHEAT | ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FRENZY, "Redline Frenzy" },
};

// Tar Pit combines Sluggish and Gravity in a separate rare pool.
// Gravity scales with ship speed so full throttle can still overcome the pull.
const EndlessTheme endlessSluggishThemes[] = {
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_GRAVITY,                           "Tar Pit" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING, "Quicksand" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FRENZY,      "Quagmire" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_SWIFT,       "Sinkhole" },
	{ ENDLESS_MOD_SLUGGISH | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_FORTIFIED,   "Abyss" },
};

// Dead Generator disables shield recharge and starves the main gun, but leaves other weapons usable.
const EndlessTheme endlessDeadgenThemes[] = {
	{ ENDLESS_MOD_DEADGEN,                            "Dead Reactor" },
	{ ENDLESS_MOD_DEADGEN | ENDLESS_MOD_DEVASTATING,  "Defenseless" },
	{ ENDLESS_MOD_DEADGEN | ENDLESS_MOD_FRENZY,       "Powerless" },
	{ ENDLESS_MOD_DEADGEN | ENDLESS_MOD_SWIFT,        "Brownout" },
	{ ENDLESS_MOD_DEADGEN | ENDLESS_MOD_ELITEPACK,    "Cold Start" },
};

// Martyrdom emits one tier-scaled radial burst per linked enemy unless the shot pool is nearly full.
const EndlessTheme endlessMartyrdomThemes[] = {
	{ ENDLESS_MOD_MARTYRDOM,                            "Martyrdom" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_FORTIFIED,    "Last Rites" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_ELITEPACK,    "Dead Man's Volley" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_SWIFT,        "Parting Shot" },
	{ ENDLESS_MOD_MARTYRDOM | ENDLESS_MOD_DEVASTATING,  "Final Salvo" },
};

// Seeker Rounds gives each enemy projectile one limited correction after launch.
const EndlessTheme endlessSeekerThemes[] = {
	{ ENDLESS_MOD_SEEKER,                            "Seeker Rounds" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_SWIFT,        "Guided Fire" },   // the +4 Seeker+Swift synergy sector
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_FRENZY,       "Smart Swarm" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_DEVASTATING,  "Lock On" },
	{ ENDLESS_MOD_SEEKER | ENDLESS_MOD_FORTIFIED,    "Tracker Rounds" },
};

// This table names bare omnidirectional gravity; generation adds the cosmetic OMNI bit separately.
// Unnamed combinations fall back to their plain-gravity name.
static const EndlessTheme endlessGravityOmniThemes[] = {
	{ ENDLESS_MOD_GRAVITY | ENDLESS_MOD_GRAVITY_OMNI, "Rogue Well" },
};

// Gambit names pair compatible boons and dangers; unlisted pairs use generic labels.
static const EndlessTheme endlessMixedThemes[] = {
	// Pairs.
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FORTIFIED,   "Can Opener" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FRENZY,      "Return Fire" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_SWIFT,       "Quickdraw" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_DEVASTATING, "Standoff" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_ELITEPACK,   "Giant Slayer" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_GRAVITY,     "Heavy Hitter" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_ENRAGE,      "Beat the Clock" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_SHIELDLESS,  "All In" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_TOPSY,       "Topsy Duel" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_FRENZY,         "Paper Storm" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_SWIFT,          "Glass Darts" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_ELITEPACK,      "Brittle Elites" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_ENRAGE,         "Short Fuse" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_GRAVITY,        "Feather Fall" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_OVERCLOCK,      "Blur" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_SHIELDLESS,     "Trade Blows" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FORTIFIED,     "War of Patience" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FRENZY,        "Slow Motion" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_DEVASTATING,   "Read the Room" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_ELITEPACK,     "Matrix" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_GRAVITY,       "Deep Focus" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_ENRAGE,        "Steady Hand" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_SHIELDLESS,    "Cold Read" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_TOPSY,         "Slow Spin" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FORTIFIED,       "Big Game" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FRENZY,          "Hot Zone" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_SWIFT,           "High Stakes" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_DEVASTATING,     "Danger Pay" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_ELITEPACK,       "Trophy Hunt" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_GRAVITY,         "Deep Dive" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_ENRAGE,          "Overtime" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_OVERCLOCK,       "Rush Job" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_SHIELDLESS,      "Hazard Bonus" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FORTIFIED,   "Grind" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FRENZY,      "Trigger Happy" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_SWIFT,       "Fast Hands" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_ELITEPACK,   "Cull the Herd" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_ENRAGE,      "Second Wind" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_GRAVITY,     "Dig In" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_FORTIFIED,        "Toll Road" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_SWIFT,            "Hazard Discount" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_DEVASTATING,      "Combat Pay" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_FRENZY,           "Loss Leader" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_FORTIFIED,    "Sledge" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_SWIFT,        "Piercer" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_ELITEPACK,    "Headhunter" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_FORTIFIED,    "Snowball" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_ELITEPACK,    "Killstreaker" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_SLIPSTREAM,     "Blitz" },
	{ ENDLESS_MOD_SLIPSTREAM | ENDLESS_MOD_BOUNTY,      "Smash and Grab" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_SLIPSTREAM,    "Time Warp" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_SLIPSTREAM,  "Power Play" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_SLIPSTREAM,  "Payday" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_FORTIFIED,   "Tough Crowd" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_FRENZY,      "Crowd Control" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_SWIFT,       "Skeleton Crew" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_ELITEPACK,   "Demotion" },
	{ ENDLESS_MOD_NOELITE | ENDLESS_MOD_FORTIFIED,   "Grunt Work" },
	{ ENDLESS_MOD_NOELITE | ENDLESS_MOD_DEVASTATING, "Green Troops" },
	// Pair boons and threats on independent systems.
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_DEVASTATING,       "Held Line" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_FRENZY,            "Storm Shelter" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_ELITEPACK,         "Shield Wall" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FRENZY,       "Thread the Needle" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SWIFT,        "Slip Through" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FORTIFIED,    "Small Target" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_FRENZY,       "Flak Run" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_FORTIFIED,    "Screened Advance" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_ELITEPACK,   "Paper Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_APEX,        "Hollow Crown" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_ELITEPACK,  "Silent Order" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_LEGION,     "Broken Chain" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_ELITEPACK,     "Chain Collapse" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_FRENZY,        "Pressure Valve" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_KAMIKAZE,    "Bounce Off" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_HOMING,      "Glancing Blows" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_ELITEPACK,   "Bumper Cars" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_STATIC,       "Backup Cells" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_DEVASTATING,  "Reserve Power" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_FORTIFIED,    "Survey Run" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_ENRAGE,       "Scout's Toll" },

	// Triples.
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,       "Armor Piercer" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Counterstrike" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Slugfest" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,       "Elite Duel" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "Trading Blows" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_GRAVITY | ENDLESS_MOD_DEVASTATING,   "Sinker" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,        "Bullet Dance" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,      "Zen Garden" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING,   "Stonewall Zen" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FRENZY,        "Slow Dance" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,             "Confetti" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,        "Glass Storm" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_ENRAGE,            "Tinderbox" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,          "Spun Glass" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,           "Bounty Board" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,        "Blood Money" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,         "Dead or Alive" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED,       "Kingpin" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Frenzy Feed" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ELITEPACK,   "Grinder" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,            "Risk Premium" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,        "Overpenetrate" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,           "Chain Lightning" },

	// Quads.
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,      "Last Word" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING, "Overmatch" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,  "Eye of the Storm" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,       "Shattering" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_ENRAGE,            "Powder Keg" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,        "Death and Taxes" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Payday Run" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_SWIFT,   "Elite Overmatch" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,      "Feeding Frenzy" },

	// Rare gambits pair two boons with danger.
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_DILATION | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Perfect Storm" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,           "Blood Bargain" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_FORTIFIED,     "High Roller" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_DEVASTATING, "Bullet Ballet" },

	// Remaining rows mirror combinations endlessPickMixBoon can generate.
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_FORTIFIED,         "Long Siege" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SWIFT,             "Deflection" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_ENRAGE,            "Hold Fast" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_GRAVITY,           "Anchor Point" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_OVERCLOCK,         "Weathered" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_TOPSY,             "Turtle" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_STATIC,            "Insulated" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SHIELDLESS,        "Last Shield" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_RETALIATION,       "Braced" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_MARTYRDOM,         "Blast Door" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SEEKER,            "Turned Aside" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SLIPSTREAM,        "Fast Guard" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SLUGGISH,          "Slow and Steady" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FORTIFIED,    "Long Burn" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FRENZY,       "Steady Feed" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_SWIFT,        "Quick Charge" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_ENRAGE,       "Endurance Run" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_GRAVITY,      "Counterweight" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_OVERCLOCK,    "Load Balance" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_ELITEPACK,    "Spare Cells" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_TOPSY,        "Gyro Power" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_SHIELDLESS,   "Idle Reactor" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_RETALIATION,  "Cool Under Fire" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_MARTYRDOM,    "Shrug Off" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_SEEKER,       "Recharged" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_SLIPSTREAM,   "Fast Charge" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_SLUGGISH,     "Trickle Charge" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_TOPSY,            "Flipped Fortune" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_STATIC,           "Power Bill" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_RETALIATION,      "Blood Wages" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_MARTYRDOM,        "Death Benefit" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_SEEKER,           "Marked Money" },
	{ ENDLESS_MOD_BOUNTY | ENDLESS_MOD_SLUGGISH,         "Slow Money" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_FORTIFIED,  "Silent Giants" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_FRENZY,     "Muffled" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_SWIFT,      "Signal Loss" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_DEVASTATING, "Dulled Edge" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_ENRAGE,     "Calm Command" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_GRAVITY,    "Quiet Descent" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_OVERCLOCK,  "Signal Jam" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_TOPSY,      "Crossed Wires" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_STATIC,     "White Noise" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_SHIELDLESS, "Radio Silence" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_RETALIATION, "No Reply" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_MARTYRDOM,  "Silent Fall" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_SEEKER,     "Lost Signal" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_SLIPSTREAM, "Clear Channel" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_SLUGGISH,   "Slow Signal" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_STATIC,         "Slow Current" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_RETALIATION,    "Even Tempo" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_MARTYRDOM,      "Drifting Debris" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_SEEKER,         "Wide Arc" },
	{ ENDLESS_MOD_DILATION | ENDLESS_MOD_SLUGGISH,       "Half Speed" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_ENRAGE,            "Rush Discount" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_GRAVITY,           "Sinking Fund" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_OVERCLOCK,         "Quick Sale" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_ELITEPACK,         "Elite Rebate" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_TOPSY,             "Upside Deal" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_STATIC,            "Surge Pricing" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_SHIELDLESS,        "Bare Bargain" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_RETALIATION,       "Grudge Rate" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_MARTYRDOM,         "Funeral Costs" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_SEEKER,            "Marked Down" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_SLIPSTREAM,        "Quick Bargain" },
	{ ENDLESS_MOD_FAVOR | ENDLESS_MOD_SLUGGISH,          "Slow Trade" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_SWIFT,        "Thinned Volley" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_DEVASTATING,  "Fewer and Harder" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_ENRAGE,       "Held Tide" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_GRAVITY,      "Sheltered Dive" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_OVERCLOCK,    "Filtered Storm" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_ELITEPACK,    "Elite Screen" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_TOPSY,        "Upside Screen" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_STATIC,       "Shielded Grid" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_SHIELDLESS,   "Thin Cover" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_RETALIATION,  "Curbed" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_MARTYRDOM,    "Blunted Burst" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_SEEKER,       "Fewer Hunters" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_SLIPSTREAM,   "Screened Run" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_SLUGGISH,     "Slow Screen" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_TOPSY,           "Glass Ceiling" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_STATIC,          "Brittle Circuit" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_RETALIATION,     "Fragile Fury" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_MARTYRDOM,       "Glass Grenade" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_SEEKER,          "Brittle Hunters" },
	{ ENDLESS_MOD_FRAGILE | ENDLESS_MOD_SLUGGISH,        "Crawl and Crush" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_FORTIFIED,   "Hollow Hulls" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_FRENZY,      "Hollow Volley" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_SWIFT,       "Toppling" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_DEVASTATING, "Heavy Hands" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_ENRAGE,      "Fading Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_GRAVITY,     "Falling Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_OVERCLOCK,   "Rushed Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_TOPSY,       "Fallen Sky" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_STATIC,      "Drained Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_SHIELDLESS,  "Bare Hunt" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_RETALIATION, "Angry Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_MARTYRDOM,   "Dying Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_SEEKER,      "Hunted Hunters" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_SLIPSTREAM,  "Passing Giants" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_SLUGGISH,    "Slow Giant Hunt" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_DEVASTATING,  "Hard to Hit" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_ENRAGE,       "Slim Odds" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_GRAVITY,      "Narrow Descent" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_OVERCLOCK,    "Slipping Through" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_ELITEPACK,    "Under Notice" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_TOPSY,        "Tucked In" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_STATIC,       "Grazed" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SHIELDLESS,   "Thin Margin" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_RETALIATION,  "Hard Target" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_MARTYRDOM,    "Between Bursts" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SEEKER,       "Slippery" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SLIPSTREAM,   "Narrow Lane" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_SLUGGISH,     "Small Steps" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_DEVASTATING,     "No Overlords" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_ENRAGE,          "Unled Fury" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_GRAVITY,         "Sinking Ranks" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_OVERCLOCK,       "Rushed Ranks" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_TOPSY,           "Upended Order" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_STATIC,          "Shocked Ranks" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_SHIELDLESS,      "Fair Fight" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_RETALIATION,     "Leaderless Rage" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_MARTYRDOM,       "Loyal to the End" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_SEEKER,          "Grunt Guidance" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_SLIPSTREAM,      "Quick Ranks" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_SLUGGISH,        "Slow Ranks" },
	{ ENDLESS_MOD_NOELITE | ENDLESS_MOD_FRENZY,          "Conscripts" },
	{ ENDLESS_MOD_NOELITE | ENDLESS_MOD_SWIFT,           "Raw Recruits" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_FRENZY,        "Rising Blast" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_DEVASTATING,   "Slugger" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_ENRAGE,        "Race the Rage" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_GRAVITY,       "Heavy Blast" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_OVERCLOCK,     "Blast Tempo" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_TOPSY,         "Inverted Blast" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_STATIC,        "Blast and Bleed" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_SHIELDLESS,    "Big Swing" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_RETALIATION,   "Trade Fire" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_MARTYRDOM,     "Blast Wake" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_SEEKER,        "Blast Tracker" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_SLIPSTREAM,    "Blast Past" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_SLUGGISH,      "Slow Sledge" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_OVERCLOCK,    "Duel of Speed" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_STATIC,       "Power Trade" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_RETALIATION,  "Answer in Kind" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_MARTYRDOM,    "Kill and Cover" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_SEEKER,       "Shoot the Curve" },
	{ ENDLESS_MOD_OVERCHARGE | ENDLESS_MOD_SLUGGISH,     "Heavy Punch" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_FRENZY,        "Feeding Time" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_SWIFT,         "Momentum Shift" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_DEVASTATING,   "Heavyweight" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_ENRAGE,        "Arms Race" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_GRAVITY,       "Gathering Speed" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_STATIC,        "Power Struggle" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_SHIELDLESS,    "Bare Knuckles" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_FORTIFIED,     "Hard Reset" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_SWIFT,         "Clean Air" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_DEVASTATING,   "Blast Radius" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_ENRAGE,        "Reset the Clock" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_GRAVITY,       "Pressure Wave" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_OVERCLOCK,     "Cadence Break" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_TOPSY,         "Spin Clear" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_STATIC,        "Ion Sweep" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_SHIELDLESS,    "Breathing Space" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_RETALIATION,   "Cut the Chain" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_MARTYRDOM,     "Blast for Blast" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_SEEKER,        "Wipe the Curve" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_SLIPSTREAM,    "Clearing Run" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_SLUGGISH,      "Slow Sweep" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_FORTIFIED,   "Shoulder Check" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_FRENZY,      "Push Through" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_SWIFT,       "Brush Past" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_DEVASTATING, "Hard Knocks" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_ENRAGE,      "Ride It Out" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_GRAVITY,     "Soft Descent" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_OVERCLOCK,   "Rough Ride" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_TOPSY,       "Roll With It" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_STATIC,      "Fender Bender" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_SHIELDLESS,  "Bare Bumper" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_RETALIATION, "Shoved Aside" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_MARTYRDOM,   "Blast Cushion" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_SEEKER,      "Nudged" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_SLIPSTREAM,  "Sideswipe" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_SLUGGISH,    "Slow Nudge" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_FRENZY,       "Fire Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_SWIFT,        "Quick Chart" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_DEVASTATING,  "Costly Chart" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_GRAVITY,      "Deep Chart" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_OVERCLOCK,    "Rushed Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_ELITEPACK,    "Guarded Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_TOPSY,        "Skewed Chart" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_STATIC,       "Static Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_SHIELDLESS,   "Bare Recon" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_RETALIATION,  "Hot Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_MARTYRDOM,    "Blast Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_SEEKER,       "Tracked Recon" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_SLIPSTREAM,   "Flyby Survey" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_SLUGGISH,     "Slow Recon" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_DEVASTATING,  "Beat the Blow" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_OVERCLOCK,    "Tempo War" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_TOPSY,        "Spin and Spray" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_STATIC,       "Spark Feed" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_SHIELDLESS,   "No Margin" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_RETALIATION,  "Tempo Duel" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_MARTYRDOM,    "Rolling Thunder" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_SEEKER,       "Outpace" },
	{ ENDLESS_MOD_TURBODRIVE | ENDLESS_MOD_SLUGGISH,     "Rooted Rush" },

	// Name triples produced when later boons are grafted onto hostile courses.
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,          "Dug In" },
	{ ENDLESS_MOD_AEGIS | ENDLESS_MOD_SWIFT | ENDLESS_MOD_DEVASTATING,         "Storm Break" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,         "Eye of the Needle" },
	{ ENDLESS_MOD_LOWPROFILE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Small Mercies" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,         "Steady Burn" },
	{ ENDLESS_MOD_AUXREACTOR | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_ENRAGE,     "War of Reserves" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,    "Bump and Run" },
	{ ENDLESS_MOD_SOFTLANDING | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,     "Traffic" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_DEVASTATING, "Domino" },
	{ ENDLESS_MOD_SHOCKWAVE | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,          "Clean Break" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_DEVASTATING, "Clay Feet" },
	{ ENDLESS_MOD_GIANTKILLER | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_FRENZY,    "Hollow Wall" },
	{ ENDLESS_MOD_CLEANSIGNALS | ENDLESS_MOD_ELITEPACK | ENDLESS_MOD_SWIFT,    "Quiet Ranks" },
	{ ENDLESS_MOD_FLAKSCREEN | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,         "Thinned Storm" },
	{ ENDLESS_MOD_STARCHARTS | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Hard Won Map" },
	{ ENDLESS_MOD_NOCHAMP | ENDLESS_MOD_FRENZY | ENDLESS_MOD_SWIFT,            "Rank and Fire" },
	{ ENDLESS_MOD_OVERBLAST | ENDLESS_MOD_FRENZY | ENDLESS_MOD_DEVASTATING,    "Sledge Storm" },
	{ ENDLESS_MOD_OVERDRIVE | ENDLESS_MOD_FORTIFIED | ENDLESS_MOD_DEVASTATING, "Rolling Start" },
};

// Lookup order is significant: specific exact-bitset pools precede general pools.
#define THEME_POOL(t) { (t), COUNTOF(t) }
static const struct { const EndlessTheme *tbl; unsigned n; } endlessThemePools[] = {
	THEME_POOL(endlessGravityOmniThemes),
	THEME_POOL(endlessHostileThemes),
	THEME_POOL(endlessMixedThemes),
	THEME_POOL(endlessKamikazeThemes),
	THEME_POOL(endlessHomingThemes),
	THEME_POOL(endlessOverloadThemes),
	THEME_POOL(endlessBoonThemes),
	THEME_POOL(endlessRareThemes),
	THEME_POOL(endlessEvilThemes),
	THEME_POOL(endlessRedlineThemes),
	THEME_POOL(endlessSluggishThemes),
	THEME_POOL(endlessDeadgenThemes),
	THEME_POOL(endlessMartyrdomThemes),
	THEME_POOL(endlessSeekerThemes),
	THEME_POOL(endlessBreakthroughThemes),
	THEME_POOL(endlessWarpThemes),
};
#undef THEME_POOL

// Find the theme for an exact effect-bit set (NULL = Calm / no modifiers).
static const EndlessTheme *endlessFindTheme(Uint64 mods)
{
	for (unsigned p = 0; p < COUNTOF(endlessThemePools); ++p)
		for (unsigned i = 0; i < endlessThemePools[p].n; ++i)
			if (endlessThemePools[p].tbl[i].mods == mods)
				return &endlessThemePools[p].tbl[i];
	// Strip cosmetic OMNI once so unnamed combinations use their plain-gravity name.
	if (mods & ENDLESS_MOD_GRAVITY_OMNI)
		return endlessFindTheme(mods & ~ENDLESS_MOD_GRAVITY_OMNI);
	return NULL;
}

// Pick a theme containing `must` and excluding `forbid`. Return `must` if none match.
Uint64 endlessPickThemeMods(const EndlessTheme *tbl, unsigned count, Uint64 must, Uint64 forbid)
{
	unsigned n = 0;
	for (unsigned i = 0; i < count; ++i)
		if ((tbl[i].mods & must) == must && (tbl[i].mods & forbid) == 0)
			++n;
	if (n == 0)
		return must;
	unsigned pick = endlessRand() % n;
	for (unsigned i = 0; i < count; ++i)
		if ((tbl[i].mods & must) == must && (tbl[i].mods & forbid) == 0)
			if (pick-- == 0)
				return tbl[i].mods;
	return must;  // unreachable
}

// Deterministic generic names for danger, boon, and mixed combinations.
// Names must be unique across tables and use font_ascii characters.
static const char *const endlessGenericNames[] = {
	"Havoc", "Chaos", "Carnage", "Ruin", "Fury", "Terror", "Doom", "Peril",
	"Menace", "Scourge", "Bedlam", "Mayhem", "Torment", "Dread", "Malice",
	"Ordeal", "Gauntlet", "Crucible", "Inferno", "Tempest", "Reckoning",
	"Oblivion", "Rampage", "Turmoil", "Onset", "Affliction",
	"Anguish", "Vengeance", "Spite", "Blight", "Bane", "Calamity",
	"Catastrophe", "Shockwave", "Aftershock", "Fallout", "Deluge", "Torrent",
	"Broadside", "Dragnet", "Crosshairs", "Deathtrap", "Minefield", "Gallows",
	"Ill Omen", "Tribulation", "Strife", "Discord", "Incursion", "Squall",
	"Whirlwind", "Ashfall", "Backdraft", "Misfortune", "Jeopardy", "Hazard",
	"Distress", "Duress", "Snare", "Pitfall", "Vendetta", "Hostile Ground",
	"Scorched Sky", "Grim Tide", "Nightfall", "Darkfall", "Downpour",
	"Hornet Nest", "Viper Pit", "Killing Floor", "Furnace", "Cauldron",
	"Ravage", "Rupture", "Sundering", "Retribution", "Reprisal",
	"Dire Straits", "Storm Front", "Headwinds", "Foul Weather", "Wasteland",
	"Badlands", "Rough Waters", "Breaking Point", "Boiling Point",
	"Fever Pitch", "Graveyard", "Onrush",
	"Abattoir", "Adversity", "Agony", "Anathema", "Ashen Sky", "Avalanche",
	"Bad Moon", "Black Ice", "Bleak Passage", "Blood Debt", "Bloodletting",
	"Brutality", "Burning Sky", "Choke Point", "Cold Comfort", "Corrosion",
	"Crossbones", "Cutthroat", "Dark Water", "Dead Air", "Dead End",
	"Death Wish", "Desperation", "Dirge", "Downfall", "Dust Storm",
	"Evil Hour", "Famine", "Fell Wind", "Firetrap", "Foul Tide", "Grief",
	"Grim Harvest", "Hail of Iron", "Hard Luck", "Hard Road", "Harrowing",
	"Hellscape", "Ice Storm", "Ill Wind", "Iron Teeth", "Jaws of Death",
	"Kill Order", "Last Breath", "Locust Swarm", "Long Night", "Lost Cause",
	"Malignant", "Mauling", "Meat Grinder", "Misery", "Molten Rain",
	"No Man's Land", "Obliteration", "Open Season", "Plague", "Poison Well",
	"Quicklime", "Rain of Fire", "Rat Trap", "Razorwind", "Red Sky",
	"Ruinous Path", "Savagery", "Scorn", "Shattered Sky", "Sinister",
	"Slaughterhouse", "Sorrow", "Stormlash", "Strangler", "Suffering",
	"Thorn Field", "Thunderhead", "Trial by Fire", "Undoing", "Unrest",
	"Venom", "Vise Grip", "War Drums", "Woe", "Wreckage",
};
static const char *const endlessBoonGenericNames[] = {
	"Godsend", "Reprieve", "Tailwind", "Grace", "Easy Street", "Good Omen",
	"Lucky Star", "Silver Lining", "Uplift", "Bright Side", "Fair Winds",
	"Respite", "Blessing", "Sanctuary", "Boon", "Windswept",
	"Serendipity", "Providence", "Good Fortune", "Charmed", "Lucky Streak",
	"Golden Hour", "Halcyon", "Oasis", "Haven", "Safe Harbor", "Safe Passage",
	"Smooth Sailing", "Clear Skies", "Blue Skies", "Daybreak", "First Light",
	"New Dawn", "Morning Star", "North Star", "Guiding Light", "Beacon",
	"Lodestar", "Godspeed", "Cakewalk", "Breather", "Mercy", "Benediction",
	"Deliverance", "Prosperity", "Abundance", "Milk Run", "Sunday Drive",
	"Scenic Route", "Fair Weather", "Green Light", "All Clear", "Home Free",
	"Open Road", "Free Ride", "Sweet Spot", "Kind Stars", "Full Sails",
	"Warm Welcome", "Gentle Current", "Good Graces", "Guardian Angel",
	"Fresh Start", "Head Start", "Helping Hand", "Stroke of Luck",
	"Free Pass", "Sunrise",
	"Auspicious", "Balm", "Bright Passage", "Calm Waters", "Carefree",
	"Clean Run", "Clear Path", "Clear Sailing", "Comfort", "Cool Breeze",
	"Easy Going", "Easy Odds", "Even Keel", "Fair Shake", "Fortunate Turn",
	"Free Rein", "Friendly Skies", "Gentle Hand", "Glad Tidings",
	"Golden Path", "Golden Ticket", "Good Tidings", "Happy Accident",
	"Harmony", "High Spirits", "Idyll", "In the Clear", "Just Rewards",
	"Kind Fortune", "Lady Luck", "Leg Up", "Light Work", "Lucky Charm",
	"Lull", "Merciful", "Mild Passage", "Nest Egg", "Nice and Easy",
	"On a Roll", "Open Water", "Paradise", "Pathfinder", "Peace of Mind",
	"Plain Sailing", "Promised Land", "Quiet Sector", "Rainbow",
	"Right of Way", "Sanctum", "Second Chance", "Serenity", "Shelter",
	"Shooting Star", "Silk Road", "Slack Water", "Smooth Ride", "Solace",
	"Steady Wind", "Still Waters", "Sunbeam", "Sunlit Path", "Tranquil",
	"Upswing", "Warm Front", "Welcome Sight", "Well Wishes", "Zephyr",
};
static const char *const endlessMixedGenericNames[] = {
	"Gambit", "Trade-off", "Bargain", "Double Edge", "Wager", "Faustian",
	"Devil's Deal", "Two-Edged", "Give and Take", "Long Shot", "Roll the Dice",
	"Loaded Dice", "Bittersweet", "Mixed Bag", "Toss-Up", "Wild Card", "Crossroads",
	"Coin Flip", "Heads or Tails", "Double Down", "Ante Up", "Calculated Risk",
	"Risky Business", "Gray Area", "Fine Print", "Hidden Cost", "Price to Pay",
	"Steep Price", "Fair Trade", "Horse Trade", "Quid Pro Quo", "Tit for Tat",
	"Tug of War", "Balancing Act", "Tightrope", "Razor's Edge", "Knife's Edge",
	"Double Bind", "Dilemma", "Conundrum", "Paradox", "Pandora's Box",
	"Poison Apple", "Forbidden Fruit", "Siren Song", "Fool's Gold",
	"Fool's Errand", "Devil's Due", "Snake Eyes", "Hedged Bet", "Side Bet",
	"Long Odds", "Even Odds", "Leap of Faith", "Blind Bargain", "Gilded Cage",
	"Mixed Blessing", "Rose and Thorn", "Gift Horse", "Trojan Horse",
	"Silver Hook", "Honey Trap", "Hard Bargain", "Push Your Luck",
	"Buyer Beware", "Sucker Bet", "Raised Stakes",
	"All or Nothing", "Bait and Switch", "Best of Both", "Big If",
	"Bitter Pill", "Blood Price", "Brass Ring", "Cash and Carry", "Caveat",
	"Cold Trade", "Costly Gift", "Cut Both Ways", "Dangerous Gift",
	"Double or Nothing", "Even Trade", "Fair Exchange", "Fine Balance",
	"Give a Little", "Gilded Trap", "Grim Bargain", "Half Measure",
	"Hard Choice", "Hedge", "High Wire", "House Rules", "In for a Penny",
	"Iron Price", "Lure", "Middle Ground", "Mixed Signals", "No Free Lunch",
	"Odd Bargain", "On the Fence", "Penny Wise", "Pick Your Poison",
	"Poisoned Well", "Price of Glory", "Pros and Cons", "Rigged Game",
	"Sharp Deal", "Six of One", "Split Decision", "Stacked Deck",
	"Sweet and Sour", "Sweetened Deal", "Take the Bait", "Thin Ice",
	"Trade Winds", "Two Way Street", "Uneasy Truce", "Velvet Trap",
	"Weigh the Odds", "With Strings",
};

static const char *endlessAllTableName(unsigned index, Uint64 *mods)
{
	for (unsigned p = 0; p < COUNTOF(endlessThemePools); ++p)
	{
		if (index < endlessThemePools[p].n)
		{
			if (mods != NULL)
				*mods = endlessThemePools[p].tbl[index].mods;
			return endlessThemePools[p].tbl[index].name;
		}
		index -= endlessThemePools[p].n;
	}

	static const struct { const char *const *names; unsigned n; } genericPools[] = {
		{ endlessGenericNames,      COUNTOF(endlessGenericNames) },
		{ endlessBoonGenericNames,  COUNTOF(endlessBoonGenericNames) },
		{ endlessMixedGenericNames, COUNTOF(endlessMixedGenericNames) },
	};
	for (unsigned p = 0; p < COUNTOF(genericPools); ++p)
	{
		if (index < genericPools[p].n)
		{
			if (mods != NULL)
				*mods = 0;
			return genericPools[p].names[index];
		}
		index -= genericPools[p].n;
	}
	return NULL;
}

static bool endlessTableNameValid(const char *name)
{
	if (name == NULL || name[0] == '\0' || strlen(name) >= 24)
		return false;  // menuInt course labels are char[24]
	for (const unsigned char *p = (const unsigned char *)name; *p != '\0'; ++p)
		if (*p != ' ' && font_ascii[*p] < 0)
			return false;
	return true;
}

bool endlessValidateModifierTables(char *detail, size_t detailSize)
{
	Uint64 registered = 0;
	unsigned nameCount = 0;
	for (unsigned p = 0; p < COUNTOF(endlessThemePools); ++p)
		nameCount += endlessThemePools[p].n;
	nameCount += COUNTOF(endlessGenericNames) + COUNTOF(endlessBoonGenericNames)
	           + COUNTOF(endlessMixedGenericNames);

	if (detail != NULL && detailSize != 0)
		detail[0] = '\0';

	for (unsigned i = 0; i < COUNTOF(endlessModTable); ++i)
	{
		const Uint64 bit = endlessModTable[i].bit;
		if (bit == 0 || (bit & (bit - 1)) != 0 || (registered & bit) != 0)
		{
			if (detail != NULL && detailSize != 0)
				snprintf(detail, detailSize, "modifier row %u has a zero, composite, or duplicate bit", i);
			return false;
		}
		registered |= bit;
	}

	for (unsigned i = 0; i < nameCount; ++i)
	{
		Uint64 mods = 0;
		const char *name = endlessAllTableName(i, &mods);
		if (!endlessTableNameValid(name))
		{
			if (detail != NULL && detailSize != 0)
				snprintf(detail, detailSize, "name row %u is empty, too long, or contains an invisible glyph", i);
			return false;
		}
		if (mods != 0)
		{
			if ((mods & ~(registered | ENDLESS_MOD_GRAVITY_OMNI)) != 0
			 || ((mods & ENDLESS_MOD_GRAVITY_OMNI) && !(mods & ENDLESS_MOD_GRAVITY))
			 || endlessCanonicalMods(mods) != mods   // a special-enemy bit a stronger one covers
			 || endlessPopCount64(mods & ENDLESS_MOD_KILLFIRE_ANY) > 1)
			{
				if (detail != NULL && detailSize != 0)
					snprintf(detail, detailSize, "theme '%s' has an unknown or incompatible modifier set", name);
				return false;
			}
		}
		for (unsigned j = i + 1; j < nameCount; ++j)
		{
			const char *other = endlessAllTableName(j, NULL);
			if (strcmp(name, other) == 0)
			{
				if (detail != NULL && detailSize != 0)
					snprintf(detail, detailSize, "duplicate course name '%s'", name);
				return false;
			}
		}
	}

	return true;
}

// `salt` advances generated names to resolve per-visit collisions. Curated names ignore it.
const char *endlessComboNameSalted(Uint64 mods, unsigned salt)
{
	if (mods & ENDLESS_MOD_THEEND)
		return "The End";                  // the finale is named by its marker, whatever dangers it rolled
	const EndlessTheme *t = endlessFindTheme(mods);
	if (t)
		return t->name;                    // curated combos keep their cool names
	if (mods == 0)
		return "Calm Sector";
	// Mask OMNI so unnamed combinations share their plain-gravity generated name.
	Uint64 key = mods & ~ENDLESS_MOD_GRAVITY_OMNI;
	Uint64 h = (key ^ (key >> 4) ^ (key >> 9)) + salt;  // mix so nearby bitsets differ
	// Classify off the danger/boon masks so the generated name matches the sector's tone. Cursed counts
	// hostile-side (it's a trap), matching how the monitor lists it.
	const bool hasHostile = (key & (ENDLESS_HOSTILE_MASK | ENDLESS_MOD_CURSED)) != 0;
	const bool hasBoon    = (key & ENDLESS_BOON_MASK) != 0;
	if (hasBoon && hasHostile)
		return endlessMixedGenericNames[h % COUNTOF(endlessMixedGenericNames)];
	if (hasBoon)
		return endlessBoonGenericNames[h % COUNTOF(endlessBoonGenericNames)];
	return endlessGenericNames[h % COUNTOF(endlessGenericNames)];
}

// Tier words, grades, and rewards share the net-danger score.

// Survival boons reduce net danger; economic boons do not.
static const struct { Uint64 bit; int credit; } endlessBoonMitigation[] = {
	{ ENDLESS_MOD_DILATION,    8 },  // enemy shots crawl: the biggest dodge cushion
	{ ENDLESS_MOD_FRAGILE,     8 },  // frail foes die fast: fewer guns left firing
	{ ENDLESS_MOD_NOELITE,     8 },  // removes elite and champion tiers
	{ ENDLESS_MOD_NOCHAMP,     5 },  // no champions: drops the nastiest tier (1.7x fire, +50% shot dmg, fat HP)
	{ ENDLESS_MOD_OVERCHARGE,  5 },  // shots hit harder: quicker kills
	{ ENDLESS_MOD_OVERDRIVE,   5 },  // Turbodrive + Overblast together: quickened guns and stacking damage
	{ ENDLESS_MOD_OVERBLAST,   4 },  // each kill stacks damage
	{ ENDLESS_MOD_TURBODRIVE, 3 },  // each kill quickens the guns
	// The later survival boons. Star Charts and Breakthrough are absent on purpose: their reward lands
	// at the NEXT outpost, so they buy no safety inside the sector and must not soften its tier.
	{ ENDLESS_MOD_LOWPROFILE,  7 },  // a quarter off the hitbox: the broadest dodge cushion of the set
	{ ENDLESS_MOD_AEGIS,       5 },  // the shield can no longer be punched through in one hit
	{ ENDLESS_MOD_FLAKSCREEN,  5 },  // suppresses half of added tide shots
	{ ENDLESS_MOD_GIANTKILLER, 5 },  // elites/champions die at ordinary speed, so their guns leave the fight sooner
	{ ENDLESS_MOD_CLEANSIGNALS,4 },  // the special tier stops firing fast and hitting hard
	{ ENDLESS_MOD_SOFTLANDING, 3 },  // ramming stops being a death sentence (projectiles still are)
	{ ENDLESS_MOD_SHOCKWAVE,   3 },  // each special kill buys a moment of clear air
	{ ENDLESS_MOD_AUXREACTOR,  3 },  // shields refill without starving the guns
};

// Synergy bonuses contribute to both danger and payout. Matching entries stack.
static const struct { Uint64 combo; int bonus; } endlessSynergies[] = {
	{ ENDLESS_MOD_SLUGGISH   | ENDLESS_MOD_GRAVITY,     8 },  // Tar Pit
	{ ENDLESS_MOD_SLUGGISH   | ENDLESS_MOD_KAMIKAZE,    7 },  // slowed while rammers home in
	{ ENDLESS_MOD_DEADGEN    | ENDLESS_MOD_FORTIFIED,   6 },  // starved guns against fortified hulls
	{ ENDLESS_MOD_SLUGGISH   | ENDLESS_MOD_HOMING,      5 },  // slowed vs light homing: dodging no longer shakes it
	{ ENDLESS_MOD_FORTIFIED  | ENDLESS_MOD_ENRAGE,      5 },  // longer fights allow more Enrage scaling
	{ ENDLESS_MOD_SHIELDLESS | ENDLESS_MOD_DEVASTATING, 5 },  // no regen and every hit lands harder: one mistake sticks
	{ ENDLESS_MOD_SLUGGISH   | ENDLESS_MOD_FRENZY,      4 },  // half the reach to thread twice the bullets
	{ ENDLESS_MOD_SWIFT      | ENDLESS_MOD_HOMING,      4 },  // fast homing shots
	{ ENDLESS_MOD_TOPSY      | ENDLESS_MOD_GRAVITY,     4 },  // a flipped view AND a pull: which way is up, and away?
	{ ENDLESS_MOD_SEEKER      | ENDLESS_MOD_SWIFT,     4 },  // fast guided shots
	{ ENDLESS_MOD_RETALIATION | ENDLESS_MOD_ENRAGE,    5 },  // a kill-storm stacked on the time-based fire climb: it screams fastest exactly when you clear hardest
};

// Total synergy bonus for a modifier set: every combo whose bits are all present, summed (they stack).
int endlessSynergyBonus(Uint64 mods)
{
	int b = 0;
	for (unsigned i = 0; i < COUNTOF(endlessSynergies); ++i)
		if ((mods & endlessSynergies[i].combo) == endlessSynergies[i].combo)
			b += endlessSynergies[i].bonus;
	return b;
}

// Net danger is hostile weight minus survival credit, plus the level's base danger.
// Calm and boon routes remain at zero; hostile routes floor at one.
int endlessDangerScoreEx(Uint64 mods, int baseDanger)
{
	const Uint64 h = mods & ENDLESS_HOSTILE_MASK;
	if (h == 0)
		return 0;   // clean/boon course: always Calm and always first, regardless of the level's baseDanger
	int t = 0;
	for (unsigned i = 0; i < COUNTOF(endlessModTable); ++i)
		if (h & endlessModTable[i].bit)
			t += endlessModTable[i].reward;
	for (unsigned i = 0; i < COUNTOF(endlessBoonMitigation); ++i)
		if (mods & endlessBoonMitigation[i].bit)
			t -= endlessBoonMitigation[i].credit;
	t += endlessSynergyBonus(mods);   // combos worse than the sum of their parts
	t += baseDanger;
	return (t < 1) ? 1 : t;   // a hostile course never reads below Low, even on a gentle level
}

int endlessDangerScore(Uint64 mods)
{
	return endlessDangerScoreEx(mods, 0);
}

// Return a registry phrase for external screens, or "" for label-only bits.
const char *endlessModWord(Uint64 bit)
{
	for (unsigned i = 0; i < COUNTOF(endlessModTable); ++i)
		if (endlessModTable[i].bit == bit)
			return endlessModTable[i].word ? endlessModTable[i].word : "";
	return "";
}

// One ladder drives tier words and grades. The final row is the unbounded catch-all.
static const struct { int maxScore; const char *tier; } endlessDangerBands[] = {
	{  9, "Low"        },  // grade E; hostile courses floor at score 1
	{ 13, "Moderate"   },  // grade D
	{ 19, "Tough"      },  // grade C
	{ 26, "High"       },  // grade B
	{ 33, "Severe"     },  // grade A
	{ 39, "Deadly"     },  // grade S
	{ 49, "Extreme"    },  // grade S+
	{ 59, "NIGHTMARE"  },  // grade S++
	{  0, "APOCALYPSE" },  // grade S+++; maxScore unused
};

// Which rung of the ladder a hostile score lands on: 0 (mildest) .. COUNTOF-1 (the catch-all).
static unsigned endlessDangerBand(int score)
{
	unsigned b = 0;
	while (b + 1 < COUNTOF(endlessDangerBands) && score > endlessDangerBands[b].maxScore)
		++b;
	return b;
}

// Tier word shown before a course's description: a one-glance risk read off the net danger score.
// A modifier-only or Cursed route reads Boon; its monitor rows show any economic drawback.
const char *endlessDangerTierEx(Uint64 mods, int baseDanger)
{
	if (mods & ENDLESS_MOD_THEEND) return "FINALITY";  // the 100th-zone finale, a rung above APOCALYPSE
	const int score = endlessDangerScoreEx(mods, baseDanger);
	if (score == 0) return (mods == 0) ? "Calm" : "Boon";  // no danger at all: clean/boon AND a gentle level
	return endlessDangerBands[endlessDangerBand(score)].tier;
}

const char *endlessDangerTier(Uint64 mods)
{
	return endlessDangerTierEx(mods, 0);
}

// Grade level 0 is F, 1..9 map through the ladder, and 10 is the finale.
// game_menu.c uses the same value to select the rank tint.
int endlessDangerRankLevelEx(Uint64 mods, int baseDanger)
{
	if (mods & ENDLESS_MOD_THEEND) return 10;   // END is the finale grade
	const int score = endlessDangerScoreEx(mods, baseDanger);
	if (score == 0) return 0;                   // F has no combat danger
	return 1 + (int)endlessDangerBand(score);   // E .. S+++
}

int endlessDangerRankLevel(Uint64 mods)
{
	return endlessDangerRankLevelEx(mods, 0);
}
// Grade 10 belongs only to the finale. Keep this array aligned with endlessRankHue[].
static const char *const endlessRankName[11] = { "F", "E", "D", "C", "B", "A", "S", "S+", "S++", "S+++", "END" };
const char *endlessDangerRankEx(Uint64 mods, int baseDanger)
{
	return endlessRankName[endlessDangerRankLevelEx(mods, baseDanger)];
}

const char *endlessDangerRank(Uint64 mods)
{
	return endlessDangerRankEx(mods, 0);
}

// Per-level intrinsic danger.
// The generated table is keyed by episode and lvlFileNum. Missing levels are neutral.
int endlessLevelBaseDanger(int ep, int file, int difficulty)
{
	if (difficulty < 0)
		difficulty = 0;
	else if (difficulty > 10)
		difficulty = 10;
	for (unsigned i = 0; i < COUNTOF(endlessLevelProfiles); ++i)
		if (endlessLevelProfiles[i].ep == ep && endlessLevelProfiles[i].file == file)
			return endlessLevelProfiles[i].baseDanger[difficulty];
	return 0;
}

// Payout adjustment is independent of baseDanger and uses thousandths of the base reward.
int endlessLevelPayoutMille(int ep, int file, int difficulty)
{
	if (difficulty < 0)
		difficulty = 0;
	else if (difficulty > 10)
		difficulty = 10;
	for (unsigned i = 0; i < COUNTOF(endlessLevelProfiles); ++i)
		if (endlessLevelProfiles[i].ep == ep && endlessLevelProfiles[i].file == file)
			return endlessLevelProfiles[i].payoutMille[difficulty];
	return 0;
}

int endlessLevelLengthClass(int ep, int file)
{
	for (unsigned i = 0; i < COUNTOF(endlessLevelProfiles); ++i)
		if (endlessLevelProfiles[i].ep == ep && endlessLevelProfiles[i].file == file)
			return endlessLevelProfiles[i].lengthClass;
	return 1;
}
