#ifndef OPENTYRIAN_VERSION_H
#define OPENTYRIAN_VERSION_H

#ifndef OPENTYRIAN_VERSION
#define OPENTYRIAN_VERSION "Engaged v1.4.1"
#endif

#ifndef OPENTYRIAN_COMMIT
#define OPENTYRIAN_COMMIT ""
#endif

#endif // OPENTYRIAN_VERSION_H
